config:
  - constraint_target_yaw: true
    target_vel: 0.01
    max_velocity: 1
    max_accelation: 0.3
    max_omega: 1.1
    kp:
      x: 3
      y: 2.5
      yaw: 2
    allow_start_dir_error: 0.02
    allow_final_dir_error: 0.02
    allow_final_pos_allow: 0.02
    adjust_min_vel: 0.5
    adjust_min_omega: 0.4
    allow_y_vel: false
    trajectory_connection_radius: 0
    stand_at_target: false
    stand_duration: 0