#真实箱子的位置
arm_box_positions:
  # 真实放置区 4 个槽位，索引按 box_id 对应，格式为 [x, y]
  arm_place:
    - [5.125, -0.8] # box_id 0
    - [5.125, -1.6] # box_id 1
    - [5.125, -2.4] # box_id 2
    - [5.125, -3.2] # box_id 3
  # 真实抓取区第一排 4 个槽位，格式为 [x, y]
  arm_pick_row_0:
    - [2.325, -0.725]  # col 0
    - [2.325, -1.575]  # col 1
    - [2.325, -2.425]  # col 2
    - [2.325, -3.275]  # col 3
  # 真实抓取区第二排 4 个槽位，格式为 [x, y]
  arm_pick_row_1:
    - [1.475, -0.725] # col 0
    - [1.475, -1.575] # col 1
    - [1.475, -2.425] # col 2
    - [1.475, -3.275] # col 3

#狗子要跑到的位置，不是箱子的位置
box_positions:
  # 放置区 4 个槽位，索引按 box_id 对应，格式为 [x, y, yaw]
  place:
    - [4.555, -0.725, 0.0] # box_id 0
    - [4.555, -1.575, 0.0] # box_id 1
    - [4.555, -2.425, 0.0] # box_id 2
    - [4.555, -3.275, 0.0] # box_id 3
  # 抓取区第一排 4 个槽位，格式为 [x, y, yaw]
  pick_row_0:
    - [2.97, -0.725, 3.1415926] # col 0
    - [2.97, -1.575, 3.1415926] # col 1
    - [2.97, -2.425, 3.1415926] # col 2
    - [2.97, -3.275, 3.1415926] # col 3
  # 抓取区第二排 4 个槽位，格式为 [x, y, yaw]
  pick_row_1:
    - [2.027, -0.725, 3.1415926] # col 0
    - [2.027, -1.575, 3.1415926] # col 1
    - [2.027, -2.425, 3.1415926] # col 2
    - [2.027, -3.275, 3.1415926] # col 3