arm_task:
  ros__parameters:
    arm_task: 0
    air_pump: false
    use_vision_grasp: false
    base_frame: arm_base_link
    camera_frame: camera_link
    object_frame: object_frame
    arm_calc_node_name: arm_calc_node
    vision_model_node_name: arm_node

    positions:
      ready: [0.0, 2.1, 2.0, 3.0]
      home: [0.0, 0.1, 0.1, 0.0]
      place_level_1: [0.0, 1.7, 2.8, 3.3]
      place_level_2: [0.0, 1.7, 2.8, 3.3]
      look_for: [0.0, 1.2, 2.3, 2.8]
      grasp_finish: [0.0, 0.1, 0.1, -0.8]
      release_box: [0.0, 1.8, 3.8, 0.6]
      re_grasp_box: [0.0, 0.7, 3.3, -0.9]
      re_grasp_box_collision_avoid: [0.0, 1.57, 3.14, -1.2]
      place_box_collision_avoid: [0.0, 0.9, 3.14, -1.1]
      finished_release_box: [0.0, 1.8, 2.0, 0.6]

    poses:
      grasp_z: -0.15
      rady_grasp_z: 0.1
      place_level_1_z: 0.06
      place_level_2_z: 0.15
      pitch_offset: -0.37

    vision:
      grasp_threshold_variance: 0.1

    timing:
      pump_on_wait_ms: 600
      record_ready_duration: 0.7
      grasp_ready_duration: 0.2
      grasp_pregrasp_duration: 0.3
      grasp_descend_duration: 0.3
      grasp_lift_duration: 0.4
      grasp_finish_duration: 1.7
      release_box_duration: 2.1
      release_collision_avoid_duration: 0.2
      release_home_duration: 0.35
      place_hand_level_1_prepare_duration: 2.4
      place_hand_level_1_cartesian_duration: 0.8
      place_hand_level_1_home_duration: 0.3
      place_hand_level_2_prepare_duration: 3.0
      place_hand_level_2_cartesian_duration: 0.8
      place_hand_level_2_retract_duration: 0.2
      place_hand_level_2_home_duration: 0.5
      place_box_re_grasp_duration: 1.0
      place_box_re_grasp_collision_avoid_duration: 0.8
      place_box_collision_avoid_duration: 0.1
      place_box_level_1_prepare_duration: 3.5
      place_box_level_1_cartesian_duration: 0.6
      place_box_level_1_home_duration: 0.3
      place_box_level_2_prepare_duration: 3.5
      place_box_level_2_cartesian_duration: 1.0
      place_box_level_2_retract_duration: 0.2
      place_box_level_2_home_duration: 0.5
      look_for_prepare_duration: 1.5
      scan_start_duration: 0.2
      scan_home_duration: 0.5

    scan:
      start_joint_0: -0.4
      stop_joint_0: 0.4
      initial_wait_sec: 5.0
      sweep_duration: 8.0
